name: billetera
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # Versiones más recientes que solucionan el problema PigeonUserDetails
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_core: ^3.6.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.7
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true