// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP6-ltLp2DrxNeASqd_R72n-dmR7IcvFQ',
    appId: '1:249611086911:web:dc4504a8aeca280a5b5c8a',
    messagingSenderId: '249611086911',
    projectId: 'billetera-9f01e',
    authDomain: 'billetera-9f01e.firebaseapp.com',
    storageBucket: 'billetera-9f01e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2_xMCAENG3Zo8jSJjJPsQde6VIMWKvhQ',
    appId: '1:249611086911:android:0516d9112b3bd6695b5c8a',
    messagingSenderId: '249611086911',
    projectId: 'billetera-9f01e',
    storageBucket: 'billetera-9f01e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4ixR5yIy3_0lbiN3_c_1lyThGELG1Lmc',
    appId: '1:249611086911:ios:bc4d0c8c408f211a5b5c8a',
    messagingSenderId: '249611086911',
    projectId: 'billetera-9f01e',
    storageBucket: 'billetera-9f01e.firebasestorage.app',
    iosBundleId: 'com.example.billetera',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4ixR5yIy3_0lbiN3_c_1lyThGELG1Lmc',
    appId: '1:249611086911:ios:bc4d0c8c408f211a5b5c8a',
    messagingSenderId: '249611086911',
    projectId: 'billetera-9f01e',
    storageBucket: 'billetera-9f01e.firebasestorage.app',
    iosBundleId: 'com.example.billetera',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDP6-ltLp2DrxNeASqd_R72n-dmR7IcvFQ',
    appId: '1:249611086911:web:e9385b1a79abd0555b5c8a',
    messagingSenderId: '249611086911',
    projectId: 'billetera-9f01e',
    authDomain: 'billetera-9f01e.firebaseapp.com',
    storageBucket: 'billetera-9f01e.firebasestorage.app',
  );
}
